const TYPES=['สินทรัพย์หมุนเวียน','สินทรัพย์ไม่หมุนเวียน','หนี้สินหมุนเวียน','หนี้สินไม่หมุนเวียน','ทุน','รายได้','ถอนใช้ส่วนตัว'];
const conceptSets=[
[['ข้อใดอธิบายความหมายของ “สินทรัพย์” ได้ถูกต้อง','ทรัพยากรที่กิจการควบคุมและคาดว่าจะให้ประโยชน์ในอนาคต',['ภาระที่ต้องชำระ','สิทธิของเจ้าหนี้','ค่าใช้จ่ายส่วนตัว']],['สินทรัพย์ที่เปลี่ยนเป็นเงินสด ขาย หรือใช้หมดภายใน 1 ปี เรียกว่าอะไร','สินทรัพย์หมุนเวียน',['สินทรัพย์ไม่หมุนเวียน','หนี้สินหมุนเวียน','ทุน']],['ที่ดิน อาคาร และเครื่องจักร จัดเป็นรายการใด','สินทรัพย์ไม่หมุนเวียน',['สินทรัพย์หมุนเวียน','หนี้สินไม่หมุนเวียน','รายได้']],['ข้อใดคือความหมายของหนี้สิน','ภาระผูกพันที่กิจการต้องชำระในอนาคต',['ทรัพยากรของกิจการ','ผลตอบแทนจากการขาย','เงินที่เจ้าของลงทุน']],['หนี้สินที่ต้องชำระภายใน 1 ปี เรียกว่าอะไร','หนี้สินหมุนเวียน',['หนี้สินไม่หมุนเวียน','สินทรัพย์หมุนเวียน','ทุน']],['เงินกู้ที่มีกำหนดชำระภายใน 5 ปี จัดเป็นอะไร','หนี้สินไม่หมุนเวียน',['หนี้สินหมุนเวียน','สินทรัพย์ไม่หมุนเวียน','รายได้']],['ส่วนของเจ้าของคำนวณได้อย่างไร','สินทรัพย์ − หนี้สิน',['สินทรัพย์ + หนี้สิน','หนี้สิน − สินทรัพย์','รายได้ − ทุน']],['เงินสดหรือสินทรัพย์ที่เจ้าของนำมาลงทุนเรียกว่าอะไร','ทุน',['รายได้','หนี้สิน','ถอนใช้ส่วนตัว']],['ผลตอบแทนจากการขายสินค้าหรือบริการเรียกว่าอะไร','รายได้',['ทุน','สินทรัพย์','ถอนใช้ส่วนตัว']],['เงินหรือสินทรัพย์ที่เจ้าของนำไปใช้ส่วนตัวเรียกว่าอะไร','ถอนใช้ส่วนตัว',['รายได้','ทุน','หนี้สิน']]],
[['สินทรัพย์แบ่งตามระยะเวลาการใช้ประโยชน์ได้กี่ประเภท','2 ประเภท',['3 ประเภท','4 ประเภท','5 ประเภท']],['เงินสดและเงินฝากธนาคารโดยทั่วไปจัดเป็นอะไร','สินทรัพย์หมุนเวียน',['สินทรัพย์ไม่หมุนเวียน','หนี้สินหมุนเวียน','ทุน']],['อาคารและอุปกรณ์สำนักงานจัดเป็นอะไร','สินทรัพย์ไม่หมุนเวียน',['สินทรัพย์หมุนเวียน','หนี้สินไม่หมุนเวียน','รายได้']],['ภาระผูกพันที่ต้องชำระในอนาคตเรียกว่าอะไร','หนี้สิน',['สินทรัพย์','รายได้','ทุน']],['เจ้าหนี้การค้าโดยทั่วไปจัดเป็นอะไร','หนี้สินหมุนเวียน',['หนี้สินไม่หมุนเวียน','สินทรัพย์หมุนเวียน','ทุน']],['เงินกู้กำหนดชำระภายใน 7 ปีจัดเป็นอะไร','หนี้สินไม่หมุนเวียน',['หนี้สินหมุนเวียน','สินทรัพย์ไม่หมุนเวียน','ถอนใช้ส่วนตัว']],['สิทธิส่วนที่เหลือของเจ้าของหลังหักหนี้สินเรียกว่าอะไร','ส่วนของเจ้าของ',['สินทรัพย์หมุนเวียน','รายได้','เจ้าหนี้']],['ผลตอบแทนจากการดำเนินงานเรียกว่าอะไร','รายได้',['ทุน','ถอนใช้ส่วนตัว','หนี้สิน']],['เมื่อกิจการมีรายได้ ส่วนของเจ้าของเป็นอย่างไร','เพิ่มขึ้น',['ลดลง','ไม่เปลี่ยนแปลง','เป็นศูนย์']],['เมื่อเจ้าของถอนเงินไปใช้ส่วนตัว ส่วนของเจ้าของเป็นอย่างไร','ลดลง',['เพิ่มขึ้น','ไม่เปลี่ยนแปลง','เป็นหนี้สิน']]],
[['ลูกหนี้การค้าและสินค้าคงเหลือจัดเป็นอะไร','สินทรัพย์หมุนเวียน',['สินทรัพย์ไม่หมุนเวียน','หนี้สินหมุนเวียน','ทุน']],['ที่ดิน อาคาร และเครื่องจักรจัดเป็นอะไร','สินทรัพย์ไม่หมุนเวียน',['สินทรัพย์หมุนเวียน','หนี้สินไม่หมุนเวียน','รายได้']],['เกณฑ์เวลาทั่วไปของสินทรัพย์หมุนเวียนคือเท่าใด','ไม่เกิน 1 ปี',['เกิน 1 ปี','ไม่เกิน 5 ปี','ไม่มีกำหนด']],['หนี้ที่ต้องชำระในรอบดำเนินงานเรียกว่าอะไร','หนี้สินหมุนเวียน',['หนี้สินไม่หมุนเวียน','สินทรัพย์หมุนเวียน','ทุน']],['เงินกู้ระยะยาวจัดเป็นอะไร','หนี้สินไม่หมุนเวียน',['หนี้สินหมุนเวียน','สินทรัพย์ไม่หมุนเวียน','รายได้']],['สมการบัญชีที่ถูกต้องคือข้อใด','สินทรัพย์ = หนี้สิน + ส่วนของเจ้าของ',['สินทรัพย์ = รายได้ + ค่าใช้จ่าย','หนี้สิน = สินทรัพย์ + ทุน','ทุน = หนี้สิน + รายได้']],['ทุนหมายถึงอะไร','เงินหรือสินทรัพย์ที่เจ้าของนำมาลงทุน',['เงินที่ถอนใช้ส่วนตัว','ผลตอบแทนจากลูกค้า','ภาระที่ต้องชำระ']],['รายได้มีผลต่อส่วนของเจ้าของอย่างไร','ทำให้เพิ่มขึ้น',['ทำให้ลดลง','ไม่เปลี่ยนแปลง','ทำให้เป็นศูนย์']],['ถอนใช้ส่วนตัวหมายถึงอะไร','เงินหรือสินทรัพย์ที่เจ้าของนำไปใช้ส่วนตัว',['ค่าใช้จ่ายของกิจการ','เงินกู้ของกิจการ','รายได้ของกิจการ']],['ถอนใช้ส่วนตัวมีผลต่อส่วนของเจ้าของอย่างไร','ทำให้ลดลง',['ทำให้เพิ่มขึ้น','ไม่เปลี่ยนแปลง','ทำให้เป็นหนี้สิน']]]
];
const classItems=[
[['เงินสด',0],['เงินฝากธนาคารประเภทออมทรัพย์',0],['ลูกหนี้การค้า',0],['ตั๋วเงินรับครบกำหนดภายใน 3 เดือน',0],['สินค้าคงเหลือ',0],['วัสดุสำนักงาน',0],['ค่าเช่าจ่ายล่วงหน้า 6 เดือน',0],['รายได้ค้างรับ',0],['เงินลงทุนระยะสั้น',0],['ที่ดิน',1],['อาคารสำนักงาน',1],['เครื่องจักร',1],['รถยนต์ส่งสินค้า',1],['เครื่องใช้สำนักงาน',1],['สิทธิบัตร',1],['เจ้าหนี้การค้า',2],['ตั๋วเงินจ่ายครบกำหนดภายใน 6 เดือน',2],['เงินกู้ยืมระยะสั้น',2],['ค่าไฟฟ้าค้างจ่าย',2],['เงินเดือนค้างจ่าย',2],['รายได้รับล่วงหน้า',2],['เงินกู้ธนาคารกำหนดชำระภายใน 5 ปี',3],['หุ้นกู้กำหนดชำระภายใน 10 ปี',3],['หนี้สินตามสัญญาเช่าระยะยาว',3],['เจ้าของนำเงินสดมาลงทุน',4],['เจ้าของนำอุปกรณ์สำนักงานมาลงทุน',4],['รายได้จากการขายสินค้า',5],['รายได้ค่าบริการ',5],['เจ้าของถอนเงินสดไปใช้ส่วนตัว',6],['เจ้าของนำสินค้าของกิจการไปใช้ที่บ้าน',6]],
[['เงินสดย่อย',0],['เงินฝากธนาคารกระแสรายวัน',0],['ลูกหนี้อื่น',0],['ตั๋วเงินรับครบกำหนดภายใน 10 เดือน',0],['สินค้าสำเร็จรูป',0],['วัตถุดิบคงเหลือ',0],['ค่าเบี้ยประกันจ่ายล่วงหน้า',0],['ดอกเบี้ยค้างรับ',0],['เงินลงทุนชั่วคราว',0],['ที่ดินที่ตั้งสำนักงาน',1],['อาคารโรงงาน',1],['อุปกรณ์คอมพิวเตอร์',1],['เฟอร์นิเจอร์สำนักงาน',1],['รถบรรทุก',1],['ลิขสิทธิ์',1],['เจ้าหนี้ค่าสินค้า',2],['ค่าน้ำประปาค้างจ่าย',2],['ภาษีค้างจ่าย',2],['ดอกเบี้ยค้างจ่าย',2],['ตั๋วเงินจ่ายครบกำหนดภายใน 1 ปี',2],['เงินกู้กำหนดชำระภายใน 8 เดือน',2],['เงินกู้จำนองกำหนดชำระภายใน 8 ปี',3],['หุ้นกู้ระยะยาว',3],['ภาระผูกพันผลประโยชน์พนักงานระยะยาว',3],['เจ้าของนำรถยนต์มาลงทุน',4],['เจ้าของนำเงินฝากธนาคารมาลงทุน',4],['รายได้ค่าเช่า',5],['รายได้ค่านายหน้า',5],['เจ้าของถอนเงินจากธนาคารไปใช้ส่วนตัว',6],['เจ้าของนำอุปกรณ์กิจการไปใช้ส่วนตัว',6]],
[['เงินฝากธนาคาร',0],['เช็ครับลงวันที่ภายใน 30 วัน',0],['ลูกหนี้การค้า',0],['สินค้าระหว่างผลิต',0],['วัสดุสิ้นเปลือง',0],['ค่าโฆษณาจ่ายล่วงหน้า',0],['ค่าบริการค้างรับ',0],['ตั๋วเงินรับครบกำหนดภายใน 1 ปี',0],['เงินลงทุนระยะสั้นในหลักทรัพย์',0],['อาคารร้านค้า',1],['เครื่องตกแต่งร้าน',1],['เครื่องถ่ายเอกสาร',1],['รถยนต์ของกิจการ',1],['เครื่องหมายการค้า',1],['เงินลงทุนระยะยาว',1],['เจ้าหนี้การค้า',2],['ค่าเช่าอาคารค้างจ่าย',2],['ค่าจ้างพนักงานค้างจ่าย',2],['เงินรับล่วงหน้าจากลูกค้า',2],['เงินกู้กำหนดชำระภายใน 4 เดือน',2],['หนี้ระยะยาวส่วนที่ถึงกำหนดใน 1 ปี',2],['เงินกู้ธนาคารกำหนดชำระภายใน 10 ปี',3],['หนี้ตามสัญญาเช่ากำหนดชำระภายใน 6 ปี',3],['ตั๋วเงินจ่ายระยะยาว',3],['เจ้าของนำอาคารมาลงทุน',4],['เจ้าของนำเครื่องจักรมาลงทุน',4],['รายได้ดอกเบี้ย',5],['รายได้จากการให้บริการ',5],['เจ้าของถอนเงินสดไปจ่ายส่วนตัว',6],['เจ้าของนำสินค้าของร้านไปให้เป็นของขวัญส่วนตัว',6]]
];
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
function makeSet(i){const c=conceptSets[i].map((x,n)=>({id:`c${n}`,q:x[0],answer:x[1],choices:shuffle([x[1],...x[2]])}));const d=classItems[i].map((x,n)=>({id:`d${n}`,q:`รายการ “${x[0]}” จัดอยู่ในประเภทใด`,answer:TYPES[x[1]],choices:shuffle(TYPES.filter((_,j)=>j!==x[1]).slice(0,3).concat(TYPES[x[1]]))}));return shuffle([...c,...d]);}
const CONFIG={
  // หากเปิดเว็บจาก Google Apps Script ไม่ต้องแก้ค่านี้
  // หากโฮสต์เว็บแยกต่างหาก ให้วาง URL ของ Web app หลัง Deploy Code.gs
  appsScriptUrl:'https://script.google.com/macros/s/AKfycbzaOVO7-knqZtu5DVgPKHtIBot6kId2EUZORRpgMjkq5OdLC3-p0xBx8qq4cOnLU34/exec'
};
const EXAM_SECONDS=40*60;
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const inAppsScript=()=>typeof google!=='undefined'&&google.script&&google.script.run;
let state={screen:'login',student:null,set:null,questions:[],answers:{},index:0,started:null,seconds:EXAM_SECONDS,syncStatus:'idle',teacherPin:''};
function shell(content){return `<header class="top"><div class="topin"><div class="brand"><span class="brandmark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M3 5.5c3-1.4 6-1 9 1.2v13c-3-2.1-6-2.5-9-1.2v-13Zm18 0c-3-1.4-6-1-9 1.2v13c3-2.1 6-2.5 9-1.2v-13Z"/></svg></span><span>แบบทดสอบออนไลน์ การบัญชีเบื้องต้น<small>สำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 4</small></span></div><div class="equation">สินทรัพย์ = หนี้สิน + ส่วนของเจ้าของ</div></div></header>${content}<footer class="foot">แบบทดสอบ 40 ข้อ · เวลา 40 นาที · บันทึกผลผ่าน Google Sheet</footer>`}
function render(){if(state.screen==='login')login();if(state.screen==='exam')exam();if(state.screen==='result')result();if(state.screen==='admin')admin();}
function login(){
  app.innerHTML=shell(`<main class="wrap loginwrap"><section class="panel login"><div class="loginhead"><div class="loginicon" aria-hidden="true">✓</div><div><h1>เข้าสู่ระบบสอบ</h1><p class="sub">กรอกรหัสประจำตัวนักเรียน 5 หลัก ระบบจะแสดงข้อมูลให้อัตโนมัติ</p></div></div><form id="loginForm"><div class="field"><label for="sid">รหัสประจำตัวนักเรียน</label><div class="lookup-input"><input id="sid" inputmode="numeric" maxlength="5" required autocomplete="off" autofocus placeholder="กรอกรหัส 5 หลัก"><span id="lookupIcon" aria-hidden="true"></span></div><p id="lookupMessage" class="lookup-message" aria-live="polite">รองรับรายชื่อนักเรียนชั้น ม.4/3</p></div><div id="studentProfile" class="student-profile hidden" aria-live="polite"><div class="student-avatar" aria-hidden="true">✓</div><div><strong id="studentName"></strong><span id="studentMeta"></span></div></div><div class="instructions"><strong>คำแนะนำก่อนเริ่มทำแบบทดสอบ</strong><ul><li>แบบทดสอบมีทั้งหมด 40 ข้อ ข้อละ 1 คะแนน</li><li>มีเวลาทำ 40 นาที ระบบจะส่งคำตอบเมื่อหมดเวลา</li><li>เมื่อส่งคำตอบแล้วจะไม่สามารถแก้ไขได้</li></ul></div><button id="startExam" class="btn primary wide" type="submit" disabled><span aria-hidden="true">▶</span> เริ่มทำแบบทดสอบ</button></form><button id="teacher" class="teacherlink" type="button">สำหรับครู: ดูผลคะแนนนักเรียน</button><div class="connection ${inAppsScript()||CONFIG.appsScriptUrl?'connected':'local'}"><span></span>${inAppsScript()||CONFIG.appsScriptUrl?'เชื่อมต่อ Google Sheet พร้อมใช้งาน':'โหมดทดสอบในเครื่อง — ตั้งค่า Web app URL ก่อนใช้งานจริง'}</div></section></main>`);
  const sidInput=$('#sid'),profile=$('#studentProfile'),message=$('#lookupMessage'),startButton=$('#startExam'),icon=$('#lookupIcon');
  let selectedStudent=null;
  let lookupSequence=0;
  async function lookupStudent(){
    const sid=sidInput.value.replace(/\D/g,'').slice(0,5);
    let lookupFailed=false;
    if(sidInput.value!==sid)sidInput.value=sid;
    selectedStudent=null;
    const sequence=++lookupSequence;
    if(sid.length===5){
      message.textContent='กำลังตรวจสอบรหัสนักเรียน…';
      message.className='lookup-message';
      try{
        const response=await lookupStudentRemote(sid);
        if(sequence!==lookupSequence)return;
        selectedStudent=response&&response.found?response.student:null;
      }catch(error){
        if(sequence!==lookupSequence)return;
        console.error(error);
        lookupFailed=true;
        message.textContent='เชื่อมต่อรายชื่อนักเรียนไม่สำเร็จ กรุณาแจ้งครูผู้สอน';
        message.className='lookup-message error';
      }
    }
    profile.classList.toggle('hidden',!selectedStudent);
    startButton.disabled=!selectedStudent;
    icon.textContent=selectedStudent?'✓':'';
    icon.className=selectedStudent?'found':'';
    sidInput.classList.toggle('valid',Boolean(selectedStudent));
    sidInput.classList.toggle('invalid',sid.length===5&&!selectedStudent);
    if(selectedStudent){
      $('#studentName').textContent=selectedStudent.name;
      $('#studentMeta').textContent=`รหัส ${selectedStudent.sid} · ห้อง ${selectedStudent.room}`;
      message.textContent='ตรวจสอบข้อมูลแล้ว สามารถเริ่มทำแบบทดสอบได้';
      message.className='lookup-message success';
    }else{
      if(!lookupFailed){
        message.textContent=sid.length===5?'ไม่พบรหัสนี้ในรายชื่อนักเรียน ม.4/3':'รองรับรายชื่อนักเรียนชั้น ม.4/3';
        message.className=sid.length===5?'lookup-message error':'lookup-message';
      }
    }
  }
  sidInput.oninput=lookupStudent;
  $('#loginForm').onsubmit=e=>{e.preventDefault();if(!selectedStudent){alert('กรุณารอให้ระบบตรวจสอบรหัสนักเรียนให้เรียบร้อย');sidInput.focus();return}const {sid,name,room}=selectedStudent;const old=records().find(x=>x.sid===sid);if(old&&!confirm('พบผลสอบของรหัสนี้ในเครื่องแล้ว ต้องการเริ่มใหม่หรือไม่?'))return;const set=Math.floor(Math.random()*3);state={screen:'exam',student:{sid,name,room},set,questions:makeSet(set),answers:{},index:0,started:Date.now(),seconds:EXAM_SECONDS,syncStatus:'idle',teacherPin:''};sessionStorage.setItem('examState',JSON.stringify(state));startTimer();render();window.scrollTo(0,0)};
  $('#teacher').onclick=()=>{if(!inAppsScript()&&!CONFIG.appsScriptUrl){alert('กรุณาตั้งค่า Apps Script Web app URL ก่อนเปิดหน้าครู');return}const pin=prompt('กรอกรหัสสำหรับครู');if(pin!==null){state.teacherPin=pin;state.screen='admin';render();window.scrollTo(0,0)}};
}
let timer;function startTimer(){clearInterval(timer);timer=setInterval(()=>{state.seconds--;sessionStorage.setItem('examState',JSON.stringify(state));const t=$('#timer');if(t)t.textContent=time(state.seconds);if(state.seconds<=0){clearInterval(timer);submitExam(true)}},1000)}function time(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function exam(){const q=state.questions[state.index],answered=Object.keys(state.answers).length,pct=Math.round(answered/40*100);app.innerHTML=shell(`<div class="examhead"><div class="studentmeta"><strong>${esc(state.student.name)}</strong><span>${esc(state.student.sid)} · ${esc(state.student.room)} · ชุดสุ่ม ${state.set+1}</span></div><div><span>ความคืบหน้า</span><strong>${answered} / 40 ข้อ</strong><div class="progress"><i style="width:${pct}%"></i></div></div><div class="timebox"><span>เวลาคงเหลือ</span><strong id="timer" class="timer">${time(state.seconds)}</strong></div></div><main class="wrap examgrid"><section class="panel question"><div class="qnum">ข้อที่ ${state.index+1} / 40</div><h2>${esc(q.q)}</h2><div class="choices">${q.choices.map((x,i)=>`<label class="choice ${state.answers[q.id]===x?'selected':''}"><input type="radio" name="ans" value="${i}" ${state.answers[q.id]===x?'checked':''}><span class="radiofake" aria-hidden="true"></span><span><b>${i+1}.</b> ${esc(x)}</span></label>`).join('')}</div><div class="actions"><button class="btn outline" id="prev" ${state.index===0?'disabled':''}>‹ ข้อก่อนหน้า</button><button class="btn primary" id="next">${state.index===39?'ตรวจสอบก่อนส่ง':'ถัดไป ›'}</button></div></section><aside class="panel side"><h3>คำถาม 1–40</h3><div class="statuskeys"><span><i class="key currentkey"></i>กำลังทำ</span><span><i class="key donekey"></i>ตอบแล้ว</span><span><i class="key"></i>ยังไม่ได้ตอบ</span></div><div class="nums">${state.questions.map((x,i)=>`<button class="nbtn ${state.answers[x.id]?'done':''} ${i===state.index?'current':''}" data-i="${i}" aria-label="ไปข้อ ${i+1}">${i+1}</button>`).join('')}</div><button class="btn teal wide submitbtn" id="submit">ส่งคำตอบ</button><p class="legend">เมื่อส่งคำตอบแล้ว จะไม่สามารถแก้ไขได้</p></aside></main>`);document.querySelectorAll('input[name=ans]').forEach((el,i)=>el.onchange=()=>{state.answers[q.id]=q.choices[i];save();exam()});document.querySelectorAll('.nbtn').forEach(b=>b.onclick=()=>{state.index=+b.dataset.i;save();exam();window.scrollTo(0,0)});$('#prev').onclick=()=>{state.index--;save();exam();window.scrollTo(0,0)};$('#next').onclick=()=>{if(state.index<39){state.index++;save();exam();window.scrollTo(0,0)}else reviewSubmit()};$('#submit').onclick=reviewSubmit;}
function save(){sessionStorage.setItem('examState',JSON.stringify(state))}function reviewSubmit(){const missing=40-Object.keys(state.answers).length;if(missing&& !confirm(`ยังไม่ได้ตอบ ${missing} ข้อ ต้องการส่งคำตอบหรือไม่?`))return;if(!missing&&!confirm('ยืนยันส่งคำตอบ? เมื่อส่งแล้วจะไม่สามารถแก้ไขได้'))return;submitExam(false)}async function submitExam(auto){clearInterval(timer);const score=state.questions.reduce((s,q)=>s+(state.answers[q.id]===q.answer),0);const rec={...state.student,set:state.set+1,score,percent:score*2.5,submitted:new Date().toISOString(),duration:EXAM_SECONDS-state.seconds,auto,answeredCount:Object.keys(state.answers).length};const rs=records().filter(x=>x.sid!==rec.sid);rs.push(rec);localStorage.setItem('accountingExamResults',JSON.stringify(rs));sessionStorage.removeItem('examState');state.record=rec;state.syncStatus='saving';state.screen='result';render();window.scrollTo(0,0);try{const response=await saveResultRemote(rec);state.syncStatus=response&&response.offline?'local':'saved'}catch(error){console.error(error);state.syncStatus='local'}render()}
function result(){const r=state.record,mins=Math.floor(r.duration/60),secs=String(r.duration%60).padStart(2,'0');const sync=state.syncStatus==='saving'?'<div class="sync saving"><span></span>กำลังบันทึกผลลง Google Sheet…</div>':state.syncStatus==='saved'?'<div class="sync saved">✓ บันทึกผลลง Google Sheet เรียบร้อยแล้ว</div>':'<div class="sync local">! เก็บสำรองในเครื่องแล้ว กรุณาแจ้งครูผู้สอน</div>';app.innerHTML=shell(`<main class="wrap"><section class="panel result"><div class="resultcheck">✓</div><h1>ทำแบบทดสอบเสร็จสิ้น</h1><p>${esc(r.name)} · ${esc(r.room)}</p><div class="scoreline"><div><span>คะแนนของคุณ</span><strong>${r.score} <small>/ 40</small></strong></div><div><span>คิดเป็นร้อยละ</span><strong>${r.percent.toFixed(2)}<small>%</small></strong></div></div><div class="resultmeta"><span>ระยะเวลาในการทำข้อสอบ <b>${mins}:${secs} นาที</b></span><span>สถานะ <b>ส่งแล้ว</b></span></div>${sync}<button class="btn primary wide" onclick="location.reload()">กลับหน้าหลัก</button></section></main>`)}
function records(){try{return JSON.parse(localStorage.getItem('accountingExamResults'))||[]}catch{return[]}}
function gasCall(name,...args){return new Promise((resolve,reject)=>google.script.run.withSuccessHandler(resolve).withFailureHandler(reject)[name](...args))}
async function saveResultRemote(rec){if(inAppsScript())return gasCall('saveResult',rec);if(CONFIG.appsScriptUrl){await fetch(CONFIG.appsScriptUrl,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',record:rec})});return{ok:true}}return{ok:false,offline:true}}
function jsonp(params){return new Promise((resolve,reject)=>{const cb=`examCb_${Date.now()}_${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),timeout=setTimeout(()=>done(new Error('หมดเวลารอการตอบกลับ')),12000);function done(error,data){clearTimeout(timeout);delete window[cb];script.remove();error?reject(error):resolve(data)}window[cb]=data=>done(null,data);script.onerror=()=>done(new Error('เชื่อมต่อ Google Sheet ไม่สำเร็จ'));script.src=`${CONFIG.appsScriptUrl}?${new URLSearchParams({...params,callback:cb})}`;document.head.appendChild(script)})}
async function lookupStudentRemote(sid){if(inAppsScript())return gasCall('lookupStudent',sid);if(CONFIG.appsScriptUrl)return jsonp({action:'lookup',sid});throw new Error('ยังไม่ได้ตั้งค่า Apps Script Web app URL')}
async function getResultsRemote(pin){if(inAppsScript())return gasCall('getResults',pin);if(CONFIG.appsScriptUrl)return jsonp({action:'list',pin});return records()}
function admin(){let rs=records();app.innerHTML=shell(`<main class="wrap adminwrap"><section class="panel admin"><div class="adminbar"><div><h1>ผลคะแนนนักเรียน</h1><p class="sub" id="adminStatus">กำลังโหลดข้อมูลผลสอบ…</p></div><div class="filters"><select id="filter"><option value="all">ทุกห้อง</option><option>ม.4/3</option><option>ม.4/4</option></select><button class="btn outline" id="csv">ส่งออก CSV</button><button class="btn primary" id="back">ออก</button></div></div><div class="tablewrap"><table><thead><tr><th>ลำดับ</th><th>รหัสนักเรียน</th><th>ชื่อ–นามสกุล</th><th>ห้องเรียน</th><th>ชุด</th><th>คะแนน (40)</th><th>ร้อยละ</th><th>วันที่และเวลาที่ส่ง</th></tr></thead><tbody id="rows"></tbody></table></div></section></main>`);function rows(f='all'){const data=rs.filter(x=>f==='all'||x.room===f);$('#rows').innerHTML=data.length?data.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.sid)}</td><td>${esc(x.name)}</td><td>${esc(x.room)}</td><td>${esc(x.set)}</td><td><strong>${esc(x.score)}/40</strong></td><td>${Number(x.percent).toFixed(2)}</td><td>${new Date(x.submitted).toLocaleString('th-TH')}</td></tr>`).join(''):`<tr><td colspan="8" class="empty">ยังไม่มีผลสอบ</td></tr>`}rows();$('#filter').onchange=e=>rows(e.target.value);$('#back').onclick=()=>{state.screen='login';render()};$('#csv').onclick=()=>exportCSV(rs);getResultsRemote(state.teacherPin).then(data=>{rs=Array.isArray(data)?data:(data.results||[]);$('#adminStatus').textContent=`ข้อมูลจาก Google Sheet ทั้งหมด ${rs.length} รายการ`;rows($('#filter').value)}).catch(error=>{$('#adminStatus').textContent='เชื่อมต่อชีตไม่ได้ — แสดงข้อมูลสำรองในเครื่อง';console.error(error);rows()})}
function exportCSV(rs){const esc=x=>`"${String(x).replaceAll('"','""')}"`;const rows=[['รหัสนักเรียน','ชื่อ-นามสกุล','ห้อง','ชุดข้อสอบ','คะแนน','ร้อยละ','วันเวลา'],...rs.map(x=>[x.sid,x.name,x.room,x.set,x.score,x.percent.toFixed(2),x.submitted])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='คะแนนสอบบัญชีเบื้องต้น.csv';a.click();URL.revokeObjectURL(a.href)}
const saved=sessionStorage.getItem('examState');if(saved){try{state=JSON.parse(saved);state.seconds=Math.max(0,EXAM_SECONDS-Math.floor((Date.now()-state.started)/1000));if(state.screen==='exam')startTimer()}catch{}}render();window.scrollTo(0,0);

